### ISSUE TITLE
Validate email addresses

### ISSUE THREAD

**Issue by agustinaponte** [agustinaponte/amigoInvisible#3]
- Validate addresses so emails are not rejected due to typing errors

**Comment by kaan36875** [comment]
Do you want to check if the mail exists or only check for email structure is valid?

**Comment by agustinaponte** [comment]
I was thinking of using a regular expression to check if the string looks good for each email.

Like the first method explained here: [https://www.geeksforgeeks.org/check-if-email-address-valid-or-not-in-python/](https://www.geeksforgeeks.org/check-if-email-address-valid-or-not-in-python/)
